services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minecarte-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=db
      - DB_USER=${DB_USER?}
      - DB_PASSWORD=${DB_PASSWORD?}
      - DB_PORT=5432
      - DB_NAME=${DB_NAME?}
    depends_on:
      - db
    tty: true

  db:
    container_name: minecarte-db
    hostname: db
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME?}
      POSTGRES_USER: ${DB_USER?}
      POSTGRES_PASSWORD: ${DB_PASSWORD?}