services:
  nginx:
    image: nginx:alpine
    container_name: minecarte-nginx
    ports:
      - "8080:80"  # Port 8080 en local, 80 dans le container
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
      - websocket
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minecarte-app
    ports:
      - "3000:3000"
    command: npm run dev
    environment:
      - DATABASE_HOST=db
      - DB_USER=${DB_USER?}
      - DB_PASSWORD=${DB_PASSWORD?}
      - DB_PORT=5432
      - DB_NAME=${DB_NAME?}
    depends_on:
      - db
    tty: true

  websocket:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minecarte-ws
    ports:
      - "3002:3002"
    command: npx ts-node --project tsconfig.server.json server.ts
    environment:
      - DATABASE_HOST=db
      - DB_USER=${DB_USER?}
      - DB_PASSWORD=${DB_PASSWORD?}
      - DB_PORT=5432
      - DB_NAME=${DB_NAME?}
    depends_on:
      - db
    tty: true

  db:
    container_name: minecarte-db
    hostname: db
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME?}
      POSTGRES_USER: ${DB_USER?}
      POSTGRES_PASSWORD: ${DB_PASSWORD?}