version: "3.8"

services:
  app:
    build: .
    container_name: minecarte-app
    restart: unless-stopped
    expose:
      - "3001" # on expose uniquement en interne
    networks:
      - web

  nginx:
    image: nginx:latest
    container_name: minecarte-nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - web

  certbot:
    image: certbot/certbot
    container_name: minecarte-certbot
    volumes:
      - ./ssl:/etc/letsencrypt
    entrypoint: >
      sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done"

networks:
  web:
    driver: bridge
