import type { CollectionCard, Deck } from "./types";
import type { Action, InGameCard} from "./typesPvp";

// === Liste des actions (exemples) ===
export const actionList: Action[] = [
   { id: 1, name: "Morsure", damage: 15, cost: 1, description: "Une morsure violente.", function: "AttackOneMob", requiresTarget: true },
   { id: 2, name: "Affamé", damage: 5, cost: 0, description: "Inflige 5 PV à un mob adverse et retire une énergie à l'adversaire.", function: "voleEnergie", requiresTarget: true },
   { id: 3, name: "Table de craft", damage: 3, cost: 1, description: "Réduit le coût de la prochaine carte de 3.", function: "applyEffect"},
   { id: 4, name: "Enclume", damage: 0, cost: 0, description: "Récupère un équipement de la défausse.", function: "anvilEffect" },
   { id: 5, name: "Armure", damage: 0, cost: 2, description: "Permet de protégé le mob rattaché en soustrayant 10 dégâts à chaque attaque.", function: "armure" },
   { id: 6, name: "Coup d'ombre", damage: 10, cost: 2, description: "Inflige 10 PV à chaque mob adverse.", function: "AttackAllMobs" },
   { id: 7, name: "Soin", damage: 10, cost: 2, description: "Soigne 10 PV à un mob", function: "heal", requiresTarget: true },
   { id: 8, name: "Téléportation", damage: 0, cost: 0, description: "Pioche 1 cartes.", function: "drawCard" },
   { id: 9, name: "Téléportation Furtive", damage: 30, cost: 3, description: "Inflige 30 PV à un mob de l'adversaire & A une chance d'esquiver tous les dégâts d'une attaque lors du prochain tour", function: "attackEsquive", requiresTarget: true },
   { id: 10, name: "Explosion", damage: 60, cost: 0, description: "Inflige 60 PV et meurt instantanément ensuite.", function: "damageAndDie", requiresTarget: true },
   { id: 11, name: "Gardien du Village", damage: 0, cost: 0, description: "Passif: Si un Villageois est présent, les dégâts sont doublés.", function: "passive", autoActivate: true },
   { id: 12, name: "Tir de précision", damage: 8, cost: 0, description: "Inflige 8 PV à l'adversaire.", function: "attackDirectPlayer"},
   { id: 13, name: "Potion", damage: 10, cost: 2, description: "Soigne le mob rattaché de 10 PV à chaque tour.", function: "potionRegen" },
];


// === Liste des cartes de combat (à récupérer de la bdd) ===
export const cardList: InGameCard[] = [
  // @ts-ignore
  {
    name: "Zombie",
    imageName: "zombie",
    attack1: "Morsure",
    attack2: "Affamé",
    pv_durability: 25,
    cost: 1,
    category: "mob",
  },
  // @ts-ignore
  {
    name: "Enderman",
    imageName: "enderman",
    talent: "Téléportation",
    attack1: "Coup d'ombre",
    attack2: "Soin",
    pv_durability: 25,
    cost: 1,
    category: "mob",
  },
  // @ts-ignore
  {
    name: "Table de craft",
    imageName: "creeper", 
    effet: "Table de craft", 
    cost: 1,
    category: "artefact",
  },
  // @ts-ignore
  {
    name: "Enclume",
    imageName: "tortue",
    effet: "Enclume",
    cost: 1,
    category: "artefact",
  },
  // @ts-ignore
  {
    name: "Armure",
    imageName: "armure",
    effet: "Armure",
    cost: 2,
    category: "equipement",
  },
  // @ts-ignore
  {
    name: "Gast",
    imageName: "Gast",
    attack1: "Téléportation Furtive",
    attack2: "Explosion",
    pv_durability: 25,
    cost: 1,
    category: "mob",
  },
  // @ts-ignore
  {
    name: "Golem",
    imageName: "golem",
    talent: "Gardien du Village",
    attack1: "Morsure", // Réutilisation d'une attaque basique pour l'exemple
    attack2: "Affamé",
    pv_durability: 100,
    cost: 3,
    category: "mob",
  },
  // @ts-ignore
  {
    name: "Villageois",
    imageName: "villageois",
    talent: "Soin",
    pv_durability: 20,
    cost: 1,
    category: "mob",
  },
  // @ts-ignore
 {    
    name: "Potion",    
    imageName: "potion",    
    effet: "Potion",
    cost: 2,
    category: "equipement",
  },
];


export const exampleCollectionCards: CollectionCard[] = [
    {
        id: 1,
        name: "Creeper",
        description: "Un monstre vert qui explose",
        category: "Monstre",
        rarity: 2,
        pv_durability: 100,
        cost: 50,
        talent: null,
        attack1: 20,
        attack2: null,
        main_img: "/cards/creeper/front.png",
        background_img: "/cards/creeper/back.png",
        third_img: "/cards/creeper/mid.png",
    }, {
        id: 2,
        name: "Squelette",
        description: "Un squelette avec un arc",
        category: "Monstre",
        rarity: 3,
        pv_durability: 80,
        cost: 60,
        talent: null,
        attack1: 25,
        attack2: null,
        main_img: "/cards/skeleton/front.png",
        background_img: "/cards/skeleton/back.png",
        third_img: "/cards/skeleton/mid.png",
    }, {
        id: 3,
        name: "Zombie",
        description: "Un zombie qui pue",
        category: "Monstre",
        rarity: 1,
        pv_durability: 120,
        cost: 40,
        talent: null,
        attack1: 15,
        attack2: null,
        main_img: "/cards/zombie.png",
        background_img: "/cards/zombie.png",
        third_img: "/cards/zombie.png",
    }, {
        id: 4,
        name: "Enderman",
        description: "Un enderman qui se téléporte",
        category: "Monstre",
        rarity: 4,
        pv_durability: 90,
        cost: 70,
        talent: null,
        attack1: 30,
        attack2: null,
        main_img: "/cards/enderman.png",
        background_img: "/cards/enderman.png",
        third_img: "/cards/enderman.png",
    }, {
        id: 5,
        name: "Creeper",
        description: "Un monstre vert qui explose",
        category: "Monstre",
        rarity: 2,
        pv_durability: 100,
        cost: 50,
        talent: null,
        attack1: 20,
        attack2: null,
        main_img: "/cards/creeper/front.png",
        background_img: "/cards/creeper/back.png",
        third_img: "/cards/creeper/mid.png",
    }, {
        id: 6,
        name: "Squelette",
        description: "Un squelette avec un arc",
        category: "Monstre",
        rarity: 3,
        pv_durability: 80,
        cost: 60,
        talent: null,
        attack1: 25,
        attack2: null,
        main_img: "/cards/skeleton/front.png",
        background_img: "/cards/skeleton/back.png",
        third_img: "/cards/skeleton/mid.png",
    }, {
        id: 7,
        name: "Zombie",
        description: "Un zombie qui pue",
        category: "Monstre",
        rarity: 1,
        pv_durability: 120,
        cost: 40,
        talent: null,
        attack1: 15,
        attack2: null,
        main_img: "/cards/zombie.png",
        background_img: "/cards/zombie.png",
        third_img: "/cards/zombie.png",
    }, {
        id: 8,
        name: "Enderman",
        description: "Un enderman qui se téléporte",
        category: "Monstre",
        rarity: 4,
        pv_durability: 90,
        cost: 70,
        talent: null,
        attack1: 30,
        attack2: null,
        main_img: "/cards/enderman.png",
        background_img: "/cards/enderman.png",
        third_img: "/cards/enderman.png",
    }, {
        id: 9,
        name: "Creeper",
        description: "Un monstre vert qui explose",
        category: "Monstre",
        rarity: 2,
        pv_durability: 100,
        cost: 50,
        talent: null,
        attack1: 20,
        attack2: null,
        main_img: "/cards/creeper/front.png",
        background_img: "/cards/creeper/back.png",
        third_img: "/cards/creeper/mid.png",
    }, {
        id: 10,
        name: "Squelette",
        description: "Un squelette avec un arc",
        category: "Monstre",
        rarity: 3,
        pv_durability: 80,
        cost: 60,
        talent: null,
        attack1: 25,
        attack2: null,
        main_img: "/cards/skeleton/front.png",
        background_img: "/cards/skeleton/back.png",
        third_img: "/cards/skeleton/mid.png",
    }, {
        id: 11,
        name: "Zombie",
        description: "Un zombie qui pue",
        category: "Monstre",
        rarity: 1,
        pv_durability: 120,
        cost: 40,
        talent: null,
        attack1: 15,
        attack2: null,
        main_img: "/cards/zombie.png",
        background_img: "/cards/zombie.png",
        third_img: "/cards/zombie.png",
    }, {
        id: 12,
        name: "Enderman",
        description: "Un enderman qui se téléporte",
        category: "Monstre",
        rarity: 4,
        pv_durability: 90,
        cost: 70,
        talent: null,
        attack1: 30,
        attack2: null,
        main_img: "/cards/enderman.png",
        background_img: "/cards/enderman.png",
        third_img: "/cards/enderman.png",
    }, {
        id: 13,
        name: "Creeper",
        description: "Un monstre vert qui explose",
        category: "Monstre",
        rarity: 2,
        pv_durability: 100,
        cost: 50,
        talent: null,
        attack1: 20,
        attack2: null,
        main_img: "/cards/creeper/front.png",
        background_img: "/cards/creeper/back.png",
        third_img: "/cards/creeper/mid.png",
    }, {
        id: 14,
        name: "Squelette",
        description: "Un squelette avec un arc",
        category: "Monstre",
        rarity: 3,
        pv_durability: 80,
        cost: 60,
        talent: null,
        attack1: 25,
        attack2: null,
        main_img: "/cards/skeleton/front.png",
        background_img: "/cards/skeleton/back.png",
        third_img: "/cards/skeleton/mid.png",
    }, {
        id: 15,
        name: "Zombie",
        description: "Un zombie qui pue",
        category: "Monstre",
        rarity: 1,
        pv_durability: 120,
        cost: 40,
        talent: null,
        attack1: 15,
        attack2: null,
        main_img: "/cards/zombie.png",
        background_img: "/cards/zombie.png",
        third_img: "/cards/zombie.png",
    }, {
        id: 16,
        name: "Enderman",
        description: "Un enderman qui se téléporte",
        category: "Monstre",
        rarity: 4,
        pv_durability: 90,
        cost: 70,
        talent: null,
        attack1: 30,
        attack2: null,
        main_img: "/cards/enderman.png",
        background_img: "/cards/enderman.png",
        third_img: "/cards/enderman.png",
    }, {
        id: 17,
        name: "Creeper",
        description: "Un monstre vert qui explose",
        category: "Monstre",
        rarity: 2,
        pv_durability: 100,
        cost: 50,
        talent: null,
        attack1: 20,
        attack2: null,
        main_img: "/cards/creeper/front.png",
        background_img: "/cards/creeper/back.png",
        third_img: "/cards/creeper/mid.png",
    }, {
        id: 18,
        name: "Squelette",
        description: "Un squelette avec un arc",
        category: "Monstre",
        rarity: 3,
        pv_durability: 80,
        cost: 60,
        talent: null,
        attack1: 25,
        attack2: null,
        main_img: "/cards/skeleton/front.png",
        background_img: "/cards/skeleton/back.png",
        third_img: "/cards/skeleton/mid.png",
    }, {
        id: 19,
        name: "Zombie",
        description: "Un zombie qui pue",
        category: "Monstre",
        rarity: 1,
        pv_durability: 120,
        cost: 40,
        talent: null,
        attack1: 15,
        attack2: null,
        main_img: "/cards/zombie.png",
        background_img: "/cards/zombie.png",
        third_img: "/cards/zombie.png",
    }, {
        id: 20,
        name: "Enderman",
        description: "Un enderman qui se téléporte",
        category: "Monstre",
        rarity: 4,
        pv_durability: 90,
        cost: 70,
        talent: null,
        attack1: 30,
        attack2: null,
        main_img: "/cards/enderman.png",
        background_img: "/cards/enderman.png",
        third_img: "/cards/enderman.png",
    }
]

export const exampleDeck: Deck = {
    id: 1,
    name: "Deck de démarrage",
    cards: [
        exampleCollectionCards[0],
        exampleCollectionCards[1],
        exampleCollectionCards[2],
        exampleCollectionCards[3],
        exampleCollectionCards[4],
    ]
};
