import type { Action } from "./typesPvp";

// === Liste des actions (exemples) ===
export const actionList: Action[] = [
   // --- Actions Mobs (Seed) ---
   { id: 101, name: "Flèche rapide", damage: 10, cost: 1, description: "Inflige 10 PV à un mob adverse.", function: "AttackOneMob", requiresTarget: true, targetType: "enemy" },
   { id: 102, name: "Tir de précision", damage: 8, cost: 2, description: "Inglige 8 PV à l'adversaire.", function: "attackDirectPlayer" },
   { id: 103, name: "Croissance légendaire", damage: 0, cost: 0, description: "Un oeuf de dragon doit doit être présent sur votre plateau pour poser cette carte.", function: "defaultFunction", autoActivate: true },
   { id: 104, name: "Souffle de dragon", damage: 35, cost: 4, description: "Inflige 35 PV à chaque mob adverse.", function: "AttackAllMobs" },
   { id: 105, name: "Plonger dévastratrice", damage: 70, cost: 6, description: "Inflige 70 PV à un mob adverse.", function: "AttackOneMob", requiresTarget: true, targetType: "enemy" },
   { id: 106, name: "Récupération d'élément", damage: 0, cost: 0, description: "Permet de piocher aléatoirement une carte de votre pioche à chaque tour. Cette carte ira dans votre main.", function: "drawCard" },
   { id: 107, name: "Coup d'ombre", damage: 10, cost: 2, description: "Inflige 10 PV à chaque mob adverse.", function: "AttackAllMobs" },
   { id: 108, name: "Téléportation furtive", damage: 30, cost: 3, description: "Inflige 30 PV à un mob adverse & A une chance d'esquiver tous les dégâts d'une attaque lors du prochain tour.", function: "attackEsquive", requiresTarget: true, targetType: "enemy" },
   { id: 109, name: "Pression psychologique", damage: 0, cost: 0, description: "Si le Creeper meurt d'une attaque de l'adversaire, il inflige 15 PV à chaque mob adverse et 5 PV à l'adversaire.", function: "pressionPsychologique", autoActivate: true },
   { id: 110, name: "Explosion", damage: 60, cost: 4, description: "Inflige 60 PV et meurt instantanément après l'attaque.", function: "damageAndDie", requiresTarget: true, targetType: "enemy" },
   { id: 111, name: "Gardien du village", damage: 0, cost: 0, description: "Si un villageois est présent sur votre plateau, les attaques du golem sont multipliées par 2.", function: "passive", autoActivate: true },
   { id: 112, name: "Coup de poing de fer", damage: 25, cost: 3, description: "Inflige 25 PV à un mob adverse.", function: "AttackOneMob", requiresTarget: true, targetType: "enemy" },
   { id: 113, name: "Bon gros tank", damage: 0, cost: 2, description: "Lors du prochain tour, réduis les dégâts subis sur cette carte de 30%.", function: "applyTankEffect" },
   { id: 114, name: "Entraide", damage: 5, cost: 1, description: "Inflige 5 PV à un mob adverse pour chaque villageois présent sur le plateau (le votre et celui de votre adversaire).", function: "defaultFunction", requiresTarget: true, targetType: "enemy" },
   { id: 115, name: "Appel à un ami", damage: 0, cost: 2, description: "Si une carte Golem est présent dans vos 5 prochaines cartes à piocher, vous récupérez cette carte dans votre main.", function: "defaultFunction" },
   { id: 116, name: "Morsure", damage: 10, cost: 1, description: "Inflige 10 PV à un mob adverse.", function: "AttackOneMob", requiresTarget: true, targetType: "enemy" },
   { id: 117, name: "Affamé", damage: 5, cost: 2, description: "Inflige 5 PV à un mob adverse & Retire 1 RedStone à l'adversaire.", function: "voleEnergie", requiresTarget: true, targetType: "enemy" },
   { id: 118, name: "Morsure aquatique", damage: 5, cost: 1, description: "Inflige 5 PV à un mob adverse.", function: "AttackOneMob", requiresTarget: true, targetType: "enemy" },
   { id: 119, name: "Appel du banc", damage: 10, cost: 1, description: "Soigne un mob allié au choix de 10 PV.", function: "heal", requiresTarget: true, targetType: "ally" },
   { id: 120, name: "Carapace protectrice", damage: 0, cost: 0, description: "Lors du prochain tour, réduit les dégâts de la première attaque adverse de 50%.", function: "applyCarapaceEffect", autoActivate: true },
   { id: 121, name: "Tortue géniale", damage: 0, cost: 2, description: "Lors du prochain tour, si la Tortue meurt d'une attaque, le joueur ne prend pas les dégâts superflus.", function: "defaultFunction" },
   { id: 122, name: "Flammes perpétuelles", damage: 0, cost: 0, description: "Si ce Blaze vient de lancer une attaque, il a 50% de chance d'envoyer une boule de feu infligeant 5 PV à l'adversaire.", function: "defaultFunction", autoActivate: true },
   { id: 123, name: "Boule de feu", damage: 10, cost: 1, description: "Inflige 10 PV à tous les mobs adverses.", function: "AttackAllMobs" }, // Blaze version
   { id: 124, name: "Ralentissement calculé", damage: 1, cost: 0, description: "Retire 1 RedStone à l'adversaire.", function: "removeEnergyFromOpponent", autoActivate: true },
   { id: 125, name: "Détection sonore", damage: 0, cost: 0, description: "Si un talent adverse est activé, le mob actionneur prend 10 PV.", function: "soundDetection", autoActivate: true },
   { id: 126, name: "Réveil brutal", damage: 25, cost: 4, description: "Inflige 25 PV à chaque mob adverse.", function: "AttackAllMobs" },
   { id: 127, name: "Hurlement Sombre", damage: 40, cost: 4, description: "Inflige 40 PV à un mob adverse et l'étourdit au prochain tour.", function: "hurlementSombre", requiresTarget: true, targetType: "enemy" },
   { id: 128, name: "Lien éternel", damage: 0, cost: 0, description: "Si 2 Gardien sont présents sur votre plateau, votre santé ne peut pas descendre en dessous de 10 PV après une attaque.", function: "defaultFunction", autoActivate: true },
   { id: 129, name: "Attaque furtive", damage: 15, cost: 1, description: "Inflige 15 PV à un mob adverse.", function: "AttackOneMob", requiresTarget: true, targetType: "enemy" },
   { id: 130, name: "Rayon laser", damage: 60, cost: 5, description: "Inflige 60 PV à un mob adverse.", function: "AttackOneMob", requiresTarget: true, targetType: "enemy" },
   { id: 131, name: "Enchantement puissant", damage: 0, cost: 0, description: "Se rajoute 5 PV (même au-delà de sa vie).", function: "enchantementPuissant", autoActivate: true },
   { id: 132, name: "Potion de soin", damage: 10, cost: 2, description: "Vous soigne de 10 PV maximum.", function: "heal", requiresTarget: true, targetType: "ally" },
   { id: 133, name: "Potion explosive", damage: 20, cost: 2, description: "Inflige 20 PV à un mob adverse.", function: "AttackOneMob", requiresTarget: true, targetType: "enemy" },
   { id: 134, name: "Retour à l'envoyeur", damage: 0, cost: 0, description: "Une fois lancé, l'attaque du Ghast à 25% de chance de revenir sur lui-même.", function: "checkRetourALEnvoyeur", autoActivate: true },
   { id: 136, name: "Explosion noire", damage: 0, cost: 0, description: "Une fois que le Wither atteint 30% de ses PV, les dégâts de ses attaques sont multipliés par 2.", function: "checkWitherExplosionNoire", autoActivate: true },
   { id: 137, name: "Tête explosive", damage: 25, cost: 3, description: "Inflige 25 PV à chaque mob adverse.", function: "AttackAllMobs" },
   { id: 138, name: "Tempête du Nether", damage: 45, cost: 4, description: "Inflige 45 dégâts à un mob adverse.", function: "AttackOneMob", requiresTarget: true, targetType: "enemy" },
   { id: 139, name: "Boule de neige", damage: 5, cost: 0, description: "Inflige 5 PV à chaque mob adverse.", function: "AttackAllMobs" },
   { id: 140, name: "Encre noire", damage: 0, cost: 0, description: "La première attaque du prochain tour de votre adversaire sera attribué aléatoirement à l'un de vos mobs.", function: "encreNoire", autoActivate: true },
   { id: 141, name: "Peur viscérale", damage: 0, cost: 0, description: "Défausse aléatoirement un Creeper sur le plateau de votre adversaire.", function: "defaultFunction", autoActivate: true },
   { id: 142, name: "Coup de griffe", damage: 10, cost: 1, description: "Inflige aléatoirement entre 5 et 15 PV à un mob adverse.", function: "AttackOneMob", requiresTarget: true, targetType: "enemy" },
   { id: 143, name: "Exigence légendaire", damage: 0, cost: 0, description: "Si un Ender dragon est posé sur votre plateau, on défausse automatiquement cette carte.", function: "defaultFunction", autoActivate: true },

   // --- Artefacts / Equipements (Existants) ---
   { id: 3, name: "Table de craft", damage: 3, cost: 1, description: "Réduit le coût de la prochaine carte de 3.", function: "applyEffect"},
   { id: 4, name: "Enclume", damage: 0, cost: 1, description: "Récupère un équipement de la défausse (si disponible en surplus).", function: "anvilEffect" },
   { id: 5, name: "Armure", damage: 0, cost: 2, description: "Permet de protégé le mob rattaché en soustrayant 10 dégâts à chaque attaque.", function: "armure" },
   { id: 7, name: "Soin", damage: 10, cost: 2, description: "Soigne 10 PV à un mob", function: "heal", requiresTarget: true },
   { id: 13, name: "Potion", damage: 10, cost: 2, description: "Soigne le mob rattaché de 10 PV à chaque tour.", function: "potionRegen" },
   { id: 14, name: "Lit", damage: 25, cost: 2, description: "Soigne votre joueur de 25 dégâts.", function: "healPlayer" },
   { id: 15, name: "Livre", damage: 2, cost: 1, description: "Pioche 2 cartes.", function: "drawCardsEffect" },
   { id: 16, name: "TNT", damage: 30, cost: 2, description: "Inflige 30 dégâts à une carte ennemie.", function: "applyArtifactDamage", requiresTarget: true, targetType: "enemy" },
   { id: 17, name: "Lingot de fer", damage: 20, cost: 1, description: "Soigne 20 PV d'un Golem allié.", function: "healGolem", requiresTarget: true, targetType: "ally" },
   { id: 18, name: "End Crystal", damage: 0, cost: 2, description: "Réduit de moitié la vie d'un mob adverse. (L'armure ne fonctionne pas)", function: "halveLifeEffect", requiresTarget: true, targetType: "enemy" },
   { id: 19, name: "Ender Pearl", damage: 0, cost: 2, description: "Défausse une carte de votre plateau.", function: "discardOwnCard", requiresTarget: true, targetType: "ally" },
   { id: 20, name: "Canne à pêche", damage: 0, cost: 1, description: "75% de chance de voler 2 énergies, 25% de chance d'en donner 2.", function: "fishingRodEffect" },
   { id: 21, name: "Potion d'invisibilité", damage: 0, cost: 1, description: "Rend un mob invisible. Il ne peut pas être attaqué par l'adversaire au prochain tour.", function: "giveInvisibleEffect", requiresTarget: true, targetType: "ally" },
   { id: 22, name: "Seau de lave", damage: 10, cost: 2, description: "Applique un malus de brûlure à une carte ennemie : elle perd 10 PV à chaque tour pendant 3 tours.", function: "applyBurnEffect", requiresTarget: true, targetType: "enemy" },
   { id: 23, name: "Pomme dorée", damage: 10, cost: 2, description: "Soigne 10 PV et augmente les dégâts de 10 pendant 3 tours.", function: "applyGoldenAppleEffect", requiresTarget: true, targetType: "ally" },
   { id: 24, name: "Table d'enchantement", damage: 0, cost: 2, description: "Pendant ce tour, tous les équipements coûtent 1 énergie.", function: "applyEnchantmentTableEffect" },
   { id: 25, name: "Portail de l’End", damage: 30, cost: 2, description: "Soigne 30 PV d'un Enderman, Shulker ou Ender Dragon.", function: "healEndCreature", requiresTarget: true, targetType: "ally" },
  { id: 27, name: "Cloche", damage: 0, cost: 2, description: "Si le Warden ciblé a moins de 50% de sa vie, ses attaques coûtent 1 au prochain tour.", function: "applyBellEffect", requiresTarget: true, targetType: "ally" },
  { id: 35, name: "Lévitation", damage: 0, cost: 0, description: "Mélange une carte de la main de l'adversaire dans son deck.", function: "levitation", autoActivate: true },
  { id: 38, name: "Épée", damage: 0, cost: 0, description: "Après une attaque, inflige 5 PV à chaque mob adverse.", function: "swordEffect", autoActivate: true },
  { id: 39, name: "Pioche", damage: 0, cost: 0, description: "Au début du tour, pioche une carte supplémentaire.", function: "pickaxeEffect", autoActivate: true },
  { id: 40, name: "Bouclier", damage: 0, cost: 0, description: "Si le mob rattaché subit des attaques, inflige 10 PV au mob attaquant.", function: "shieldEffect", autoActivate: true },
  { id: 41, name: "Elitra", damage: 0, cost: 0, description: "Si le mob rattaché meurt, il est déposé dans votre main.", function: "elytraEffect", autoActivate: true },
  { id: 42, name: "Totem", damage: 0, cost: 0, description: "Si le mob meurt, il survit avec 5 PV et le Totem est détruit.", function: "totemEffect", autoActivate: true },
  { id: 43, name: "Arc", damage: 0, cost: 0, description: "Ajoute 10 dégâts aux attaques. Sur attaque de zone, cible un seul ennemi aléatoire.", function: "bowEffect", autoActivate: true },
  { id: 44, name: "Botte célérité", damage: 0, cost: 0, description: "Réduit le coût des attaques du mob de 1.", function: "speedBootsEffect", autoActivate: true },
  { id: 46, name: "Esquive", damage: 0, cost: 0, description: "45% de chance d'éviter les dégâts d'une attaque.", function: "passive", autoActivate: true },
  { id: 47, name: "Invisible", damage: 0, cost: 0, description: "Ne peut pas être ciblé par une attaque adverse.", function: "passive", autoActivate: true },
  { id: 48, name: "Stun", damage: 0, cost: 0, description: "Étourdi : Ne peut pas attaquer ce tour-ci.", function: "passive", autoActivate: true },
];
